### PR TITLE
feat: add useAnime composable

### PR DESCRIPTION
**Pull request by BayBreezy**
- add useAnime composable to module.
- add useage example to playground.
- add useage example to readme

## Type of Change

- [ ] Bug fix
- [x] New feature
- [x] Documentation
- [ ] Breaking change
- [ ] Other

## Request Description

This PR will add the `useAnime` composable once the module is installed. I added it because in Nuxt3, i dont like importing stuff manually (The Nuxt team spoiled us lolol)

This is related to the discuession started here: https://github.com/hypernym-studio/nuxt-anime/discussions/12

### CODE REVIEW

**Comment by ivodolenc** [comment]
Looks good so far.

Regarding the `auto-import`, we also need an explicit import for composable, since the user can opt-out of the [built-in](https://nuxt.com/docs/guide/concepts/auto-imports#disable-auto-imports) Nuxt feature.

So if the Nuxt `autoImport` is disabled:

```ts
// nuxt.config.ts

export default defineNuxtConfig({
  imports: {
    autoImport: false
  }
})
```

the user will be able to manually import the `composable` like this:

```html
<script setup lang="ts">
  // Explicit import (optional)
  import { useAnime } from '#anime'

  useAnime({ targets: '.title', translateX: 250, duration: 800 })
</script>
```

Also, it would be nice if the module had an `autoImport` option to be more consistent with the framework and give the user a choice, since auto-import is a opinionated feature.

Example:

```ts
// nuxt.config.ts

{
  anime: {
    autoImport: true // default is true
  }
}
```

---

Here are types for `ModuleOptions`:

```ts
export interface ModuleOptions {
  /**
   * @default undefined
   */
  composable?: boolean
  /**
   * @default undefined
   */
  autoImport?: boolean
}
```

**Review by ivodolenc — CHANGES_REQUESTED** [review]
Since we need an explicit import in case the user opts out of the built-in automatic import, I suggest extracting the composable into its own file for more control. And later we can easily assign this to an alias like this:

```ts
// module.ts
{
  setup(options, nuxt){
    // assigns the `useAnime` composable to the alias '#anime' for explicit import
    nuxt.options.alias['#anime'] = resolve('./runtime/useAnime')
  }
}

```

I believe that's mostly it, the rest shouldn't be a problem, simple if statements with options. Feel free to ask additional questions if needed.

**Comment by BayBreezy** [comment]
@ivodolenc  So i am a bit confused  when it comes on to the moduleOptions. What will the two  options do differently? 
If i pass `composable: true`, what should happen in the module? If i pass `autoImport: true`, what happens then? aren't both used to add the `useAnime` composable to the app?

**Comment by ivodolenc** [comment]
@BayBreezy Sorry if I wasn't clear enough, it might be best to split my suggestions into a new `PR` since they have a separate function from your initial proposal.

I will merge your PR that implements the new `useAnime` composable.

Also, before the final release, I will add a new `PR` with these additional suggestions.

Thanks for your time and contribution.

**Comment by BayBreezy** [comment]
@ivodolenc Ok, cool. Sorry I couldn't add it as needed. I am looking forward to your implementation 😄 . I think I might learn something

**Comment by ivodolenc** [comment]
@BayBreezy No problem, I'm glad you're interested in this module 😀

**Pull request merged**
